# Generated by Django 4.2.2 on 2024-09-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.composer')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sheets/')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.piece')),
            ],
        ),
    ]
