# Generated by Django 4.2.2 on 2024-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_piece_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
