# Generated by Django 4.2.2 on 2024-09-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_sheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
