# Generated by Django 4.2.2 on 2024-09-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_alter_sheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='file',
            field=models.FileField(upload_to='sheets/'),
        ),
    ]
