# Generated by Django 4.2.2 on 2024-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_alter_sheet_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pieces', models.ManyToManyField(to='organizer.piece')),
            ],
        ),
    ]
