# Generated by Django 4.2.2 on 2024-09-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_remove_setlist_pieces_setlist_sheets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setlist',
            name='sheets',
        ),
        migrations.CreateModel(
            name='SetListRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.setlist')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.sheet')),
            ],
        ),
    ]
