# Generated by Django 4.2.2 on 2024-09-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_remove_setlist_sheets_setlistrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='setlistrelation',
            options={'ordering': ('sheet',)},
        ),
    ]
