# Generated by Django 4.2.2 on 2024-09-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_alter_composer_options_alter_piece_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='composer',
        ),
        migrations.AddField(
            model_name='piece',
            name='composers',
            field=models.ManyToManyField(to='organizer.composer'),
        ),
    ]
