# Generated by Django 4.2.2 on 2024-09-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0010_remove_piece_composer_piece_composers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sheets', models.ManyToManyField(to='organizer.sheet')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
